name: Build Debian Package - Wheezy

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        suite: [oldstable, stable, testing]
        architecture: [amd64]
        
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: Build Debian package for ${{ matrix.suite }} on ${{ matrix.architecture }}
        uses: dawidd6/action-debian-package@v4
        with:
          os_distribution: ${{ matrix.suite }}
          cpu_architecture: ${{ matrix.architecture }}
